### ISSUE TITLE
Make `arena_alloc` aligned by default

### ISSUE THREAD

**Issue by Player01osu** [ccgargantua/arena-allocator#10]
Unaligned memory can impact performance, and thus alignment should be encouraged on allocations.

Maybe have a `#define` for default alignment.

**Comment by ccgargantua** [comment]
I like the idea, but what are your thoughts on renaming `arena_alloc` to `arena_alloc_unaligned` and renaming `arena_alloc_aligned` to `arena_alloc`? Maybe we could specify the alignment value within the `Arena` struct so that it can differ between arenas. Not sure if there is really any benefit to that, let me know your thoughts.

**Comment by Player01osu** [comment]
I was more thinking to keep the `arena_alloc` but have it call to `arena_alloc_aligned` with a default alignment set by a `#define`

**Comment by Player01osu** [comment]
> Maybe we could specify the alignment value within the Arena struct so that it can differ between arenas
This could be another approach, but I feel like differing alignment might not be too useful, since you typically want it aligned to word size anyways.

**Comment by ccgargantua** [comment]
i decided to take a swing, and i am running into some issues with determining alignment in absence of C11 `_Alignof`/`alignof`. We might need to restructure `arena_alloc_aligned` calls to have `calloc` style parameters so that we can just use the second argument (`size_t size` [here](https://en.cppreference.com/w/c/memory/calloc)) for the alignment.

With that being said, we are probably looking at something like
```c
#if __STDC_VERSION__ >= 201112L
    #include <stdalign.h>
    #define ARENA_ALIGNOF(type) alignof(type)
#else
    #define ARENA_ALIGNOF(type) offsetof(struct { char c; type d; }, d)
#endif
```
Just FYI, this hasn't been tested. If you have alternative solutions, let me know.

**Comment by ccgargantua** [comment]
> The allocated space is suitably aligned (after possible pointer coercion) for storage of any type of object.
From [malloc(3)'s man page)[https://man.freebsd.org/cgi/man.cgi?malloc(3)]

I am interpreting this as the default alignment should be the worst-case alignment, so that would probably be `alignof(size_t))`? In that case, there probably wouldn't need to be a macro for the default alignment.

**Comment by ccgargantua** [comment]
This is now addressed in a [issue10-fr](https://github.com/ccgargantua/arena-allocator/tree/issue10-fr)

While it does work, I'm not sure if it is the best solution and the tests need to be rewritten. I didn't include the change, but adding a bunch of extra space in the arena creation for `test_arena_alloc` [here](https://github.com/ccgargantua/arena-allocator/blob/9a8e21772eb368a4be6903caf62f558743bab31b/test.c#L128) results in all testing suites passing with flying colors aside from `test_arena_alloc`. Given the fact that they are already a nightmare, I think it might be wise to group in a rewrite of the testing system for the heck of it. Please take a look at the code and let me know what you think. Feel free to open a PR on that branch with whatever changes you might have, I am excited to see what you come up with :)
